config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  root "pages#index"
  get 'pages/index'
  devise_for :users, controllers:
    { registrations: 'users/registrations',
      sessions: 'users/sessions'
    } do
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bio, only: %i[index show new create destroy edit update]
  resources :consultations, only: %i[index show new create destroy edit update]
  resources :profile, only: %i[index show new create destroy edit update]
  resources :next, only: %i[index show new create destroy edit update]
  resources :exist, only: %i[index show new create destroy edit update]
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :set_consultation, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /consultations or /consultations.json
  def index
    @consultations = Consultation.all
  end

  # GET /consultations/1 or /consultations/1.json
  def show; end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit; end

  # POST /consultations or /consultations.json
  def create
    @consultation = Consultation.new(consultation_params)
    @consultation.user_id = current_user.id

    respond_to do |format|
      if @consultation.save
        format.html { redirect_to consultation_url(@consultation), notice: 'Consultation was successfully created.' }
        format.json { render :show, status: :created, location: @consultation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultations/1 or /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to consultation_url(@consultation), notice: 'Consultation was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1 or /consultations/1.json
  def destroy
    @consultation.destroy

    respond_to do |format|
      format.html { redirect_to consultations_url, notice: 'Consultation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_consultation
    @consultation = Consultation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def consultation_params
    params.require(:consultation).permit(:title, :description, :start_time, :end_time, :user_id)
  end
end

app/helpers/consultation_helper.rb
module ConsultationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_consultation.html.erb
<div id="<%= dom_id consultation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= consultation.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= consultation.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start time:</strong>
    <%= consultation.start_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End time:</strong>
    <%= consultation.end_time %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this consultation", consultation, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this consultation", edit_consultation_path(consultation), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/consultations/_form.html.erb
<%= form_with(model: consultation, class: "contents") do |form| %>
  <% if consultation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(consultation.errors.count, "error") %> prohibited this consultation from being saved:</h2>

      <ul>
        <% consultation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_time %>
    <%= form.datetime_field :start_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_time %>
    <%= form.datetime_field :end_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/consultations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing consultation</h1>

  <%= render "form", consultation: @consultation %>

  <%= link_to "Show this consultation", @consultation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to consultations", consultations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/consultations/index.html.erb
<div class="w-full p-6 sm:ml-64">
">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center">
    <h1 class="font-bold text-4xl">Consultations</h1>
    <%= link_to "New consultation", new_consultation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-black block font-medium" %>
  </div>

  <div id="consultations" class="min-w-full">
    <%= render @consultations %>
  </div>
</div>

app/views/consultations/new.html.erb
<div class="mx-auto md:w-2/3 w-full p-4 sm:ml-64">
  <h1 class="font-bold text-4xl">New consultation</h1>

  <%= render "form", consultation: @consultation %>

  <%= link_to "Back to consultations", consultations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/consultations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @consultation %>

    <%= link_to "Edit this consultation", edit_consultation_path(@consultation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this consultation", consultation_path(@consultation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to consultations", consultations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>