config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  root "pages#index"
  get 'pages/index'
  devise_for :users, controllers:
    { registrations: 'users/registrations',
      sessions: 'users/sessions'
    } do
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bio, only: %i[index show new create destroy edit update]
  resources :consultations, only: %i[index show new create destroy edit update]
  resources :profile, only: %i[index show new create destroy edit update]
  resources :next, only: %i[index show new create destroy edit update]
  resources :exist, only: %i[index show new create destroy edit update]
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user
end

app/controllers/bio_controller.rb
class BioController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @bio = Bio.all
  end

  def show
    @bio = Bio.find(params[:id])
  end

  def new
    @bio = Bio.new
  end

  def create
    @bio = Bio.new(bio_params)
    @bio.user_id = current_user.id
    respond_to do |format|
      if @bio.save
        format.html { redirect_to bio_index_path, notice: 'Bio was successfully created.' }
      else
        format.html { redirect_to bio_index_url notice: 'Failure' }
      end
    end
  end

  def destroy
    @bio = Bio.find(params[:id])
    @bio.delete
    respond_to do |format|
      format.html { redirect_to bio_index_path, notice: 'Bio was successfully deleted.' }
    end
  end

  def edit
    # Pick the bio id that matches the user id
    @bio = Bio.find(params[:id])
  end

  def update
    @bio = Bio.find(params[:id])
    respond_to do |format|
      if @bio.update(bio_params)
        format.html { redirect_to bio_index_path(@bio), notice: 'Bio was successfully updated.' }
      else
        format.html { redirect_to bio_index_url, notice: 'Failure' }
      end
    end
  end

  private

  def bio_params
    params.require(:bio).permit(:date_of_birth, :language, :home_town, :city, :country, :about_me, :health_insurance,
                                :nhif_number, :nationality, :religion, :blood_group, :hospital_to_attend, :user_id)
  end
end

app/helpers/bio_helper.rb
module BioHelper
end

app/views/bio/edit.html.erb
<div class="p-4 sm:ml-64 mt-14">


  <%= form_with(model: @bio, url: bio_path(@bio), method: :patch, class: "bg-white rounded shadow-md p-6 ") do |f| %>

  <form class="p-1 rounded-lg mt-14">
    <div class="relative z-0 w-full mb-6 group">
      <% f.label :about_me, class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
      <%= f.text_area :about_me, class: "tinymce block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer h-48", placeholder: "About me.."%>
      <%= tinymce %>
    </div>

    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <%= f.date_field :date_of_birth, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Date Of Birth." %>
        <label for="floating_first_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Date Of Birth</label>

      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= f.text_field :nationality, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Nationality." %>
        <label for="floating_last_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Nationality.</label>
      </div>
    </div>

    <div class="grid md:grid-cols-3 md:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <%= f.text_field :home_town, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Home Town" %>
        <label for="floating_first_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Home Town</label>

      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= f.text_field :city, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "City" %>
        <label for="floating_last_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">City</label>
      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= f.text_field :country, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Country" %>
        <label for="floating_last_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Country</label>
      </div>
    </div>


    <div class="grid md:grid-cols-3 md:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <%= f.text_field :health_insurance, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Home Town" %>
        <label for="floating_first_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Home Town</label>

      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= f.text_field :nhif_number, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "City" %>
        <label for="floating_last_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">City</label>
      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= f.text_field :blood_group, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-gray-50 border-0 border-b-2 border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "Country" %>
        <label for="floating_last_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Country</label>
      </div>
    </div>


    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <input type="tel" name="floating_phone" id="floating_phone" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " />
        <label for="floating_phone" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Phone number (123-456-7890)</label>
      </div>
      <div class="relative z-0 w-full mb-6 group">
        <input type="text" name="floating_company" id="floating_company" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" "  />
        <label for="floating_company" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Company (Ex. Google)</label>
      </div>
    </div>
    <%= f.submit "SUBMIT", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  </form>

  <% end %>


</div>

app/views/bio/index.html.erb
<div class="p-4 sm:ml-64 text-black">
    <% @bio.each do |bio|  %>
      <%= bio.user_id %>
      <%= bio.date_of_birth %>
      <%= bio.language  %>
      <%= bio.home_town %>
      <%= bio.about_me %>
    <% end %>
</div>

app/views/bio/show.html.erb
<div class="p-4 sm:ml-64 text-black">

    <p class="text-black">
    <%= @bio.date_of_birth %>
    <%= @bio.language  %>
    <%= @bio.home_town %>
      <%= link_to "Edit", edit_bio_path(@bio), class: "btn btn-primary" %>
    </p>

</div>

<h3>Hello</h3>This the Id:<%= @bio.user_id %><%= link_to "Edit", edit_bio_path(@bio.id), class: "text-black" %>