config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  root "pages#index"
  get 'pages/index'
  devise_for :users, controllers:
    { registrations: 'users/registrations',
      sessions: 'users/sessions'
    } do
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bio, only: %i[index show new create destroy edit update]
  resources :consultations, only: %i[index show new create destroy edit update]
  resources :profile, only: %i[index show new create destroy edit update]
  resources :next, only: %i[index show new create destroy edit update]
  resources :exist, only: %i[index show new create destroy edit update]
end

app/models/exist.rb
class Exist < ApplicationRecord
  belongs_to :user
end

app/controllers/exist_controller.rb
class ExistController < ApplicationController
  before_action :authenticate_user!
  def index; end

  def show
    @exist = Exist.find(params[:id])
  end

  def new
    @exist = Exist.new
  end

  def edit
    @exist = Exist.find(params[:id])
  end

  def create
    @exist = Exist.new(exist_params)
    @exist.user_id = current_user.id
    respond_to do |format|
      if @exist.save
        format.html { redirect_to exist_index_url(@exist), notice: 'Exist was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity, notice: 'Failure' }
      end
    end
  end

  def destroy
    @exist = Exist.find(params[:id])
    @exist.delete
    respond_to do |format|
      format.html { redirect_to exist_index_url, notice: 'Exist was successfully deleted.' }
    end
  end

  private

  def exist_params
    params.require(:exist).permit(:condition, :private, :user_id)
  end
end

app/helpers/exist_helper.rb
module ExistHelper
end

app/views/exist/edit.html.erb
<!- create an edit form -->
<div class="p-8 sm:ml-64">
  <div class="mt-14 p-4">
  <%= form_with(model: @exist, url: exist_path(@exist), method: :patch, class: "bg-white rounded shadow-md p-6") do |form| %>


        <div class="grid md:grid-cols-2 md:gap-6">
        <div class="relative z-0 w-full mb-6 group">
          <%= form.text_field :condition, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-blue-500 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "", required: true %>
          <label for="floating_first_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Condition</label>
        </div>

        <div class="relative z-0 w-full mb-6 group">
          <%= form.check_box class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" %>
          <label for="checkbox-1" class="ml-2 text-sm font-medium text-gray-900 dark:text-blue-500">Make this Condition Private </label>
        </div>
      </div>
      <%= form.submit class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      <%= button_to "Delete", @exist, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>

  <% end %>
  </div>
</div>

app/views/exist/new.html.erb
  <div class="p-8 sm:ml-64">
      <div class="mt-14 p-4">
        <%= form_with  model: @exist, url: exist_index_url, method: :post, data: { turbo: false }, local: true do |form| %>
        <div class="grid md:grid-cols-2 md:gap-6">
          <div class="relative z-0 w-full mb-6 group">
            <%= form.text_field :condition, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-blue-500 dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: "", required: true %>
            <label for="floating_first_name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Condition</label>
          </div>

          <div class="relative z-0 w-full mb-6 group">
            <%= form.check_box class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" %>
            <label for="checkbox-1" class="ml-2 text-sm font-medium text-gray-900 dark:text-blue-500">Make this Condition Private </label>
          </div>
        </div>
          <%= form.submit class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
        <% end %>
      </div>
  </div>