config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  root "pages#index"
  get 'pages/index'
  devise_for :users, controllers:
    { registrations: 'users/registrations',
      sessions: 'users/sessions'
    } do
  end

  get 'enable_otp_show_qr', to: 'users#enable_otp_show_qr', as: 'enable_otp_show_qr'
  post 'enable_otp_verify', to: 'users#enable_otp_verify', as: 'enable_otp_verify'

  get 'users/otp', to: 'users#show_otp', as: 'user_otp'
  post 'users/otp', to: 'users#verify_otp', as: 'verify_otp'
  post 'verify_otp', to: 'users/sessions#verify_otp'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bio, only: %i[index show new create destroy edit update]
  resources :consultations, only: %i[index show new create destroy edit update]
  resources :profile, only: %i[index show new create destroy edit update]
  resources :next, only: %i[index show new create destroy edit update]
  resources :exist, only: %i[index show new create destroy edit update]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.id == false
      cannot :manage, :all
    else
      can :manage, Bio, user_id: user.id
      can :manage, Consultation, user_id: user.id
      can :manage, Profile, user_id: user.id
      can :manage, Next, user_id: user.id
      can :manage, Exist, user_id: user.id

    end

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user
end

app/models/exist.rb
class Exist < ApplicationRecord
  belongs_to :user
end

app/models/next.rb
class Next < ApplicationRecord
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  devise :two_factor_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :registerable,
         :recoverable, :rememberable, :validatable

  # After User is create create a bio
  after_create :create_bio, :create_profile
  def create_bio
    Bio.create(user_id: id)
  end

  def create_profile
    Profile.create(user_id: id)
  end
  has_one :bio, foreign_key: :user_id, class_name: 'Bio', dependent: :destroy
  has_many :consultation, foreign_key: :user_id, class_name: 'Consultation', dependent: :destroy
  has_one :profile, foreign_key: :user_id, class_name: 'Profile', dependent: :destroy
end

app/controllers/bio_controller.rb
class BioController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @bio = Bio.all
  end

  def show
    @bio = Bio.find(params[:id])
  end

  def new
    @bio = Bio.new
  end

  def create
    @bio = Bio.new(bio_params)
    @bio.user_id = current_user.id
    respond_to do |format|
      if @bio.save
        format.html { redirect_to bio_index_path, notice: 'Bio was successfully created.' }
      else
        format.html { redirect_to bio_index_url notice: 'Failure' }
      end
    end
  end

  def destroy
    @bio = Bio.find(params[:id])
    @bio.delete
    respond_to do |format|
      format.html { redirect_to bio_index_path, notice: 'Bio was successfully deleted.' }
    end
  end

  def edit
    # Pick the bio id that matches the user id
    @bio = Bio.find(params[:id])
  end

  def update
    @bio = Bio.find(params[:id])
    respond_to do |format|
      if @bio.update(bio_params)
        format.html { redirect_to bio_index_path(@bio), notice: 'Bio was successfully updated.' }
      else
        format.html { redirect_to bio_index_url, notice: 'Failure' }
      end
    end
  end

  private

  def bio_params
    params.require(:bio).permit(:date_of_birth, :language, :home_town, :city, :country, :about_me, :health_insurance,
                                :nhif_number, :nationality, :religion, :blood_group, :hospital_to_attend, :user_id)
  end
end

app/controllers/exist_controller.rb
class ExistController < ApplicationController
  before_action :authenticate_user!
  def index; end

  def show
    @exist = Exist.find(params[:id])
  end

  def new
    @exist = Exist.new
  end

  def edit
    @exist = Exist.find(params[:id])
  end

  def create
    @exist = Exist.new(exist_params)
    @exist.user_id = current_user.id
    respond_to do |format|
      if @exist.save
        format.html { redirect_to exist_index_url(@exist), notice: 'Exist was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity, notice: 'Failure' }
      end
    end
  end

  def destroy
    @exist = Exist.find(params[:id])
    @exist.delete
    respond_to do |format|
      format.html { redirect_to exist_index_url, notice: 'Exist was successfully deleted.' }
    end
  end

  private

  def exist_params
    params.require(:exist).permit(:condition, :private, :user_id)
  end
end

app/controllers/next_controller.rb
class NextController < ApplicationController
  before_action :authenticate_user!

  def index
    @next = Next.all
  end

  def show
    @next = Next.find(params[:id])
  end

  def new
    @next = Next.new
  end

  def create
    @next = Next.new(next_params)
    @next.user_id = current_user.id
    respond_to do |format|
      if @next.save
        format.html { redirect_to next_url(@next), notice: 'Next was successfully created.' }
      else
        format.html { redirect_to next_index_url, notice: 'Failure' }
      end
    end
  end

  def destroy
    @next = Next.find(params[:id])
    @next.delete
    respond_to do |format|
      format.html { redirect_to next_index_path, notice: 'Next was successfully deleted.' }
    end
  end

  def edit
    @next = Next.find(params[:id])
  end

  def update
    @next = Next.find(params[:id])
    respond_to do |format|
      if @next.update(next_params)
        format.html { redirect_to next_url(@next), notice: 'Next was successfully updated.' }
      else
        format.html { redirect_to next_index_url, notice: 'Failure' }
      end
    end
  end

  private

  def next_params
    params.require(:next).permit(:name, :relationship, :phone_number, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @bio = Bio.all
    @consultations = Consultation.where(
      start_time: Time.zone.now.beginning_of_month.beginning_of_week..Time.zone.now.end_of_month.end_of_week
    )
    @profile = Profile.where(user_id: current_user.id)
    @next = Next.all.order('created_at DESC')
    @exist = Exist.all.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/consultation_helper.rb
module ConsultationHelper
end

app/helpers/exist_helper.rb
module ExistHelper
end

app/helpers/next_helper.rb
module NextHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_sidebar.html.erb
<nav class="fixed top-0 z-50 w-full bg-white border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
    <div class="px-3 py-3 lg:px-5 lg:pl-3">
        <div class="flex items-center justify-between">
            <div class="flex items-center justify-start">
                <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
                    <span class="sr-only">Open sidebar</span>
                    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
                    </svg>
                </button>
                <a href="/" class="flex ml-2 md:mr-24">
                  <%= image_tag('logo.png', class: 'h-8 mr-3 sm:h-8') %>
                  <span class="self-center text-xl font-semibold sm:text-2xl whitespace-nowrap dark:text-white">Lifeline</span>
                </a>
            </div>
            <div class="flex items-center">
                <div class="flex items-center ml-3">
                    <div>
                        <button type="button" class="flex text-sm bg-gray-800 rounded-full focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" aria-expanded="false" data-dropdown-toggle="dropdown-user">
                            <span class="sr-only">Open user menu</span>

                        </button>
                    </div>
                    <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown-user">
                        <div class="px-4 py-3" role="none">
                            <p class="text-sm text-gray-900 dark:text-white" role="none">
                                Neil Sims
                            </p>
                            <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                                neil.sims@flowbite.com
                            </p>
                        </div>
                        <ul class="py-1" role="none">
                            <li>
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Dashboard</a>
                            </li>
                            <li>
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Settings</a>
                            </li>
                            <li>
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Earnings</a>
                            </li>
                            <li>
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Sign out</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<aside id="logo-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700" aria-label="Sidebar">
    <div class="h-full px-3 pb-4 overflow-y-auto bg-white dark:bg-gray-800">
        <ul class="space-y-2 font-medium">
            <li>
                <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                        <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                        <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
                    </svg>
                    <span class="ml-3"><%= button_to "Dashboard", root_path, type: "button" , method: :get%></span>
                </a>
            </li>
            <li>
                <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"/>
                    </svg>
                    <span class="flex-1 ml-3 whitespace-nowrap">Inbox</span>
                    <span class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300">3</span>
                </a>
            </li>
            <li>
                <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" >
                    <path d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h274.9c-2.4-6.8-3.4-14-2.6-21.3l6.8-60.9 1.2-11.1 7.9-7.9 77.3-77.3c-24.5-27.7-60-45.5-99.9-45.5zm45.3 145.3l-6.8 61c-1.1 10.2 7.5 18.8 17.6 17.6l60.9-6.8 137.9-137.9-71.7-71.7-137.9 137.8zM633 268.9L595.1 231c-9.3-9.3-24.5-9.3-33.8 0l-37.8 37.8-4.1 4.1 71.8 71.7 41.8-41.8c9.3-9.4 9.3-24.5 0-33.9z"/>
                  </svg>
                  <span class="flex-1 ml-3 whitespace-nowrap"><%= button_to "Edit User", edit_user_registration_path, method: :get %></span>
                </a>
            </li>

            <li>
              <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M5 5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707A2.96 2.96 0 0 0 .13 5H5Z"/>
                  <path d="M6.737 11.061a2.961 2.961 0 0 1 .81-1.515l6.117-6.116A4.839 4.839 0 0 1 16 2.141V2a1.97 1.97 0 0 0-1.933-2H7v5a2 2 0 0 1-2 2H0v11a1.969 1.969 0 0 0 1.933 2h12.134A1.97 1.97 0 0 0 16 18v-3.093l-1.546 1.546c-.413.413-.94.695-1.513.81l-3.4.679a2.947 2.947 0 0 1-1.85-.227 2.96 2.96 0 0 1-1.635-3.257l.681-3.397Z"/>
                  <path d="M8.961 16a.93.93 0 0 0 .189-.019l3.4-.679a.961.961 0 0 0 .49-.263l6.118-6.117a2.884 2.884 0 0 0-4.079-4.078l-6.117 6.117a.96.96 0 0 0-.263.491l-.679 3.4A.961.961 0 0 0 8.961 16Zm7.477-9.8a.958.958 0 0 1 .68-.281.961.961 0 0 1 .682 1.644l-.315.315-1.36-1.36.313-.318Zm-5.911 5.911 4.236-4.236 1.359 1.359-4.236 4.237-1.7.339.341-1.699Z"/>
                </svg>
                <span class="flex-1 ml-3 whitespace-nowrap"><%= button_to "Add Appointment", new_consultation_path, method: :get %></span>
              </a>
            </li>

          <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
              <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
              </svg>

              <span class="flex-1 ml-3 whitespace-nowrap"><%= button_to "Add Next of Kin", new_next_path, method: :get %></span>
            </a>
          </li>


          <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
              <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
              </svg>

              <span class="flex-1 ml-3 whitespace-nowrap"><%= button_to "Pre Existing Condition", new_exist_path, method: :get %></span>
            </a>
          </li>

            <li>
                <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                        <path d="M17 5.923A1 1 0 0 0 16 5h-3V4a4 4 0 1 0-8 0v1H2a1 1 0 0 0-1 .923L.086 17.846A2 2 0 0 0 2.08 20h13.84a2 2 0 0 0 1.994-2.153L17 5.923ZM7 9a1 1 0 0 1-2 0V7h2v2Zm0-5a2 2 0 1 1 4 0v1H7V4Zm6 5a1 1 0 1 1-2 0V7h2v2Z"/>
                    </svg>
                    <span class="flex-1 ml-3 whitespace-nowrap"><%= button_to "Buy A Ring", edit_user_registration_path, method: :get %></span>
                </a>
            </li>
            <li>
                <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white stroke-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 16">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"/>
                    </svg>
                    <span class="flex-1 ml-3 whitespace-nowrap">
                        <%= button_to "Logout",  destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
                    </span>
                </a>
            </li>
        </ul>
    </div>
</aside>

app/views/pages/_exist.html.erb
<div class="flex flex-row rounded bg-gray-50 dark:bg-gray-800 mb-4">

  <% @exist.each do |exis| %>

    <% if can? :read, exis %>
      <%= link_to edit_exist_path(exis.id) do %>
          <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold rounded p-4  ">
            <%= exis.condition %>
          </button>
      <% end %>
    <% end %>
    <% end %>

</div>

app/views/pages/_general.html.erb
<div class="rounded bg-gray-50 dark:bg-gray-800 mb-4">
  <div>
    <div class="flex justify-between">
      <div class="pl-8 pt-4">
        <h5 class="text-2xl text-[#000] dark:text-white">General Information</h5>
      </div>
      <!--BUTTON TO ADD NEW INFORMATION-->
      <div class="p-4">
        <% @bio.each do |bio| %>
          <% if can? :read, bio %>
            <%= link_to edit_bio_path(bio.id) do %>
              <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded p-4 ">
                <!--SVG ICON ADD more information-->
                <svg class="w-4 h-4 inline-block" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
                </svg>
                Add New Information
              </button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <% @bio.each do |bio| %>
      <% if can? :read, bio %>
        <div class="p-4">
          <h5 class="text-xl text-[#000] dark:text-white p-4">
            About Me
          </h5>
          <div class="text-sm text-[#060606] dark:text-gray-300 p-4">
            <%= raw bio.about_me %>
          </div>
          <div class="text-[#060606] dark:text-white p-4">
            <div class="flex justify-start">
              <div class="gap-1 w-[50%]">
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Date of Birth</h5>
                <p class="font-semibold mb-2">
                  <%= bio.date_of_birth %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Language</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.language %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">HomeTown</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.home_town %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">City</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.city %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Country</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.country %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Health Insurance</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.health_insurance %>
                </p>
              </div>
              <div>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">NHIF Number</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.nhif_number %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Nationality</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.nationality %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Religion</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.religion %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Blood Group</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.blood_group %>
                </p>
                <h5 class="text-sm font-semibold mb-2 dark:text-gray-500">Hospital to Attend</h5>
                <p class="text-sm font-semibold mb-2">
                  <%= bio.hospital_to_attend %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>